# Site settings
title: Melon and Lemon
description: Web site design and coding
baseurl: "http://melolemo.github.io/melo-jkblog"
paginate: 5
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
