title: Melon and Lemon
description: Web Design and coding
baseurl: "http://melolemo.github/melo-jkblog"
paginate: 5
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,autolink,tables,strikethrough]
highlighter: rouge
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "melolemo"
      categories: "jekyll"
      tags: "ruby"
