# Site settings
title: Melon and Lemon
description: Web site design and coding
baseurl: "/melo-jkblog"
paginate: 5

highlighter: pygmentize
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,autolink,tables,strikethrough]

gems:
  - jekyll-sitemap
